commerce_payment.commerce_payment_gateway.plugin.paylands_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    api_key:
      type: string
      label: 'API key'
    signature:
      type: string
      label: 'Signature'
    service:
      type: string
      label: 'Service'